# 🚀 Docker Compose Complete - Solana Learn
# Para iniciar: docker-compose up --build
# Frontend: http://localhost:5173 | Backend: http://localhost:5000

version: '3.8'

services:
  # 🖥️ Backend API (Node.js + Express + TypeScript)
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: solana_learn_backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb+srv://vicridev:OvDwlhYiLfdOdhSS@db.e0byx.mongodb.net/?retryWrites=true&w=majority
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./back:/app
      - backend_node_modules:/app/node_modules
    command: npm run dev
    restart: unless-stopped

  # 🎨 Frontend (React + Vite + TypeScript)
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: solana_learn_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000/api
    volumes:
      - ./front:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    restart: unless-stopped

# Volúmenes para node_modules
volumes:
  backend_node_modules:
  frontend_node_modules: 