# 🐳 Docker Compose - Plataforma de Aprendizaje Blockchain - Proyecto DAW
# Uso: docker-compose up --build
# URLs: Frontend http://localhost:5173 | Backend http://localhost:5000

version: '3.8'

services:
  # 🗄️ MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: plataforma_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: plataforma_educativa
    volumes:
      - mongodb_data:/data/db
    networks:
      - plataforma_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🖥️ Backend API (Node.js + Express)
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: plataforma_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Configuración básica
      NODE_ENV: development
      PORT: 5000
      
      # Base de datos
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/plataforma_educativa?authSource=admin
      
      # Seguridad
      JWT_SECRET: super-secret-jwt-key-for-development-daw-project-2024
      CORS_ORIGIN: http://localhost:5173
      
      # Uploads
      UPLOAD_DIR: /app/uploads
      MAX_FILE_SIZE: 10485760
      
      # APIs opcionales
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY:-}
    volumes:
      - ./back:/app
      - backend_uploads:/app/uploads
      - backend_node_modules:/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - plataforma_network
    command: npm run dev

  # 🎨 Frontend (React + Vite)
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: plataforma_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Vite configuración
      VITE_API_URL: http://localhost:5000
      VITE_APP_ENV: development
      VITE_APP_TITLE: Plataforma de Aprendizaje Blockchain
      
      # Hot reload para desarrollo
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    volumes:
      - ./front:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - plataforma_network
    command: npm run dev -- --host 0.0.0.0

# 💾 Volúmenes persistentes
volumes:
  # Base de datos MongoDB
  mongodb_data:
    driver: local
    name: plataforma_mongodb_data
  
  # Archivos subidos por usuarios
  backend_uploads:
    driver: local
    name: plataforma_uploads
  
  # node_modules para evitar reinstalar dependencias
  backend_node_modules:
    driver: local
    name: plataforma_backend_modules
  
  frontend_node_modules:
    driver: local
    name: plataforma_frontend_modules

# 🌐 Red interna
networks:
  plataforma_network:
    driver: bridge
    name: plataforma_educativa_network 